### PR TITLE
position input inside the boundary of parent label

### PR DESCRIPTION
**Pull request by shaketbaby**
## ✍️ Proposed changes

This fixes the bug logged at https://jira.mongodb.org/browse/CHARTS-2938. It happens because the hidden input is positioned out side of the boundary box of the parent label. Fix it by move the input inside the bounding box and also set its width and height to 0 for added safety.

🎟 _Jira ticket:_ [CHARTS-2938](https://jira.mongodb.org/browse/CHARTS-2938)

## 🛠 Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by DesignerDave** [comment]
Hi – thanks for the contribution!

Changes look good to me! Would you mind generating a changeset for this change by running `yarn changeset` as documented [here](https://github.com/mongodb/leafygreen-ui#commiting)? Once that's done, this should be good to go.

**Comment by shaketbaby** [comment]
@DesignerDave thanks, have generated changeset.

**Comment by shaketbaby** [comment]
@DesignerDave @brookescarlett I don't have write access to the repository so can't merge the PR, can one of you merge it when you have some time and do a patch release. I'll update Charts to use the new version. Thanks heaps!

**Comment by brookescarlett** [comment]
@shaketbaby merged!

**Comment by shaketbaby** [comment]
@brookescarlett @DesignerDave With this merged, is it possible to do a patch release so that we can upgrade to fix [CHARTS-2938](https://jira.mongodb.org/browse/CHARTS-2938)? We are releasing v1.7 to Charts on Atlas next week and would like to have the bug fixed. Thanks!

**Comment by DesignerDave** [comment]
We're planning on doing a publish imminently, and should have this done later today.

**Pull request merged**
