### PR TITLE
Add Version Github Action

### PR DESCRIPTION
**Pull request by brookescarlett**
## ✍️ Proposed changes

- Adds version GH action

## 🛠 Types of changes

- [x] Tooling (updates to workspace config or internal tooling)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have run `yarn changeset` and documented my changes

### CODE REVIEW

**Comment by DesignerDave** [comment]
Hey Brooke! Can you clarify the behavior this would add? Does this automatically generate changelogs when a pull request is made (like `yarn changeset version`)?

**Comment by DesignerDave** [comment]
Also, what's the best way for me to verify this works as intended?

**Comment by brookescarlett** [comment]
@DesignerDave this would automatically run the equivalent of our `changeset version` every time something is pushed to master. Auomating our pre-release PR.

**Comment by brookescarlett** [comment]
Where you can see that it works: https://github.com/brookescarlett/leafygreen-ui/pull/2/files @hswolff @DesignerDave

**Pull request merged**
