### PR TITLE
PD-2160 deprecate expand-x

### PR DESCRIPTION
**Pull request by TheSonOfThomp**
## ✍️ Proposed changes

`Overflow.ExpandX` has always been an edge case, and is causing some issues with styling. Instead of increasing the complexity of the component to account for this edge case, we are removing this option. 

Rationale: in most cases the x direction will be more space-limited and not many folks will opt to use this option. And if they do use `expand-x`, it's inherently limited to the size of the container/window and we'll need to restrict the width regardless. Just providing `scroll-x` and `expand-y` overflow options will cover most use cases.

Demo: https://thesonofthomp.github.io/leafygreen-ui/?path=/story/components-combobox--multiselect&args=overflow:scroll-x

🎟 _Jira ticket:_ [PD-2160](https://jira.mongodb.org/browse/PD-2160)

## 🛠 Types of changes

- [ ] Tooling (updates to workspace config or internal tooling)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Style change (purely visual updates; if this is the case, attach a screenshot below!)

## ✅ Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have run `yarn changeset` and documented my changes

- [ ] I have added my new package to the global tsconfig
- [ ] I have added my new package to the Table of Contents on the global README

## Feedback Levels

Please try to mark your comments with one of these levels

1. Praise (👏 🚀 🔥 🍾)
2. Opinions, Ideas, Suggestions (💡 👀)
3. Let’s discuss @ Code review (🤷 🤔 🧐 )
4. Doesn’t meet agreed upon standards (😬 ⚠️ ‼️)
5. Missing an edge case (🛑 🙅 ❌)
6. Missing core functionality (⛔️ ☣️ 🚧 🌋 💀)

(Note: Use ⌘-⌃-␣ to open the Emoji keyboard!)

### CODE REVIEW

**Review by shaneeza — COMMENTED** [review]
This might be unrelated to this ticket but are we still planning on removing the tooltip on `scroll-x`? In PD-2160 it says that [PD-2164](https://jira.mongodb.org/browse/PD-2164) is a duplicate of this ticket?

**Review by alvenw — APPROVED** [review]
👏 🚀 🔥 🍾

**Comment by TheSonOfThomp** [comment]
> This might be unrelated to this ticket but are we still planning on removing the tooltip on `scroll-x`? In PD-2160 it says that [PD-2164](https://jira.mongodb.org/browse/PD-2164) is a duplicate of this ticket?

This is a separate issue I believe

**Review by shaneeza — APPROVED** [review]
🚀

**Pull request merged**
