### PR TITLE
Toast fixes LG-3090 LG-3102 LG-3103

### PR DESCRIPTION
**Pull request by TheSonOfThomp**
## ✍️ Proposed changes

- Fixes a bug where the toast stack would not expand on hover
- Fixes a bug where toasts with no description would be improperly placed when expanded

Demo: https://thesonofthomp.github.io/leafygreen-ui-fork/?path=/story/components-toast--variants

🎟 _Jira ticket:_ 
[Toasts with no description...](https://jira.mongodb.org/browse/LG-3090)
[Toasts stuck in toaster](https://jira.mongodb.org/browse/LG-3102)

### For bug fixes, new features & breaking changes

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] I have run `yarn changeset` and documented my changes

### For new components

- [ ] I have added my new package to the global tsconfig
- [ ] I have added my new package to the Table of Contents on the global README

### CODE REVIEW

**Review by sandynguyenn — CHANGES_REQUESTED** [review]
Getting this weird bug
Toast

**Comment by sandynguyenn** [comment]
Still getting same bug

Toast

**Comment by TheSonOfThomp** [comment]
> Still getting same bug


Try now, I forgot to update the link

**Review by sandynguyenn — APPROVED** [review]
Looks good now

**Review by spark33 — APPROVED** [review]

**Pull request merged**
