### PR TITLE
PD-1739 combobox single select menu behaviour (COMBOBOX #3)

### PR DESCRIPTION
**Pull request by TheSonOfThomp**
## ✍️ Proposed changes

Updates filtering behavior. Now when opening the menu, all options will be displayed regardless of whether a selection has already been made

🎟 _Jira ticket:_ [PD-1739](https://jira.mongodb.org/browse/PD-1739)

## 🛠 Types of changes

- [ ] Tooling (updates to workspace config or internal tooling)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Style change (purely visual updates; if this is the case, attach a screenshot below!)

## ✅ Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] I have run `yarn changeset` and documented my changes

- [ ] I have added my new package to the global tsconfig
- [ ] I have added my new package to the Table of Contents on the global README

## Feedback Levels

Please try to mark your comments with one of these levels

1. Praise (👏 🚀 🔥 🍾)
2. Opinions, Ideas, Suggestions (💡 👀)
3. Let’s discuss @ Code review (🤷 🤔 🧐 )
4. Doesn’t meet agreed upon standards (😬 ⚠️ ‼️)
5. Missing an edge case (🛑 🙅 ❌)
6. Missing core functionality (⛔️ ☣️ 🚧 🌋 💀)

(Note: Use ⌘-⌃-␣ to open the Emoji keyboard!)

### CODE REVIEW

**Review by shaneeza — COMMENTED** [review]
When an item is selected and the dropdown is open with all the options shown, is it expected that if you click on, say the up or down arrow, all the options will be removed except for the selected item?

**Comment by TheSonOfThomp** [comment]
> When an item is selected and the dropdown is open with all the options shown, is it expected that if you click on, say the up or down arrow, all the options will be removed except for the selected item?

Nope. Good catch!

**Review by shaneeza — COMMENTED** [review]
> if the menu is closed and an item is selected and you then use the down arrow to open the menu, the second option shows a selected state. Should it be the first item?

Yeah, I think you're right. Good catch 👍

**Comment by TheSonOfThomp** [comment]
> When using the keyboard, if the menu is closed and an item is selected and you then use the down arrow to open the menu, the second option shows a selected state. Should it be the first item?

Yeah, I think you're right 👍. fixing now

**Review by shaneeza — APPROVED** [review]
Looks great! 🔥

**Pull request merged**
