### PR TITLE
Attempt to make tests run when changeset versions branch updated

### PR DESCRIPTION
**Pull request by lazytype**
## 🛠 Types of changes

- [x] Tooling (updates to workspace config or internal tooling)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have run `yarn changeset` and documented my changes

- [ ] I have added my new package to the global tsconfig
- [ ] I have added my new package to the Table of Contents on the global README

### CODE REVIEW

**Comment by brookescarlett** [comment]
This looks good to me, but did I misread the issue that you linked to me earlier? Is the problem that it's a force push that the bot is making and actions have trouble running after force pushes?

**Comment by lazytype** [comment]
> This looks good to me, but did I misread the issue that you linked to me earlier? Is the problem that it's a force push that the bot is making and actions have trouble running after force pushes?

That's what looks to be the case to me. On the Version Packages pull request it looks like the Github Actions bot is making a force push to the branch, which doesn't trigger the "synchronize" event.

**Comment by brookescarlett** [comment]
So this is our way of circumventing that?

**Comment by lazytype** [comment]
> 
> 
> So this is our way of circumventing that?

I would say this is our way of compensating for what seems to be buggy behavior on Github's side. A possibly nicer solution might be to make the versions packages workflow action directly trigger the test workflow action to run. It wouldn't be as straight-forward, seems possible with this API https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events.

**Pull request merged**
