### PR TITLE
PD-1707 Refresh select

### PR DESCRIPTION
**Pull request by TheSonOfThomp**
## ✍️ Proposed changes

🎟 _Jira ticket:_ [Name of ticket](https://jira.mongodb.org/browse/[name-of-ticket])

## 🛠 Types of changes

- [ ] Tooling (updates to workspace config or internal tooling)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have run `yarn changeset` and documented my changes

- [ ] I have added my new package to the global tsconfig
- [ ] I have added my new package to the Table of Contents on the global README

### CODE REVIEW

**Review by shaneeza — CHANGES_REQUESTED** [review]
A few things:

- Looks like there should be a 1px border around the `<ul>`
- The top and bottom padding for each item might need to be decreased a bit so the height can get down to `32px`. It's about `36px` right now with the padding.

P.S We already spoke, but I wasn't able to check everything as yet since I have to leave early

**Review by shaneeza — CHANGES_REQUESTED** [review]
Some minor things:

- Seems like the placement of the warning icon is a little offScreen Shot 2022-01-27 at 11 24 23 AM
- The red shadow is also missing from the error state on hover
- You can see a little bit of the error message when the dropdown is openScreen Shot 2022-01-27 at 11 27 27 AM

**Comment by TheSonOfThomp** [comment]
@shaneeza Should be fixed now. Let me know if you catch anything else!

**Review by shaneeza — APPROVED** [review]
Looks great!!!

**Pull request merged**
