### PR TITLE
Added more spacing tokens

### PR DESCRIPTION
**Pull request by alvenw**
## ✍️ Proposed changes

Added spacing tokens up to 64px

🎟 _Jira ticket:_ [Name of ticket](https://jira.mongodb.org/browse/[name-of-ticket])

### For bug fixes, new features & breaking changes

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have run `yarn changeset` and documented my changes

### For new components

- [ ] I have added my new package to the global tsconfig
- [ ] I have added my new package to the Table of Contents on the global README
- [ ] I have verified the Live Example looks as intended on the design website.

### CODE REVIEW

**Comment by bruugey** [comment]
@shaneeza @TheSonOfThomp there are more tokens than hex colors hard-coded in the story file - how do we want to handle these colors moving forward?

**Comment by shaneeza** [comment]
> Details

Why do we need diff colors? Can we use the same color for all of them?

**Comment by TheSonOfThomp** [comment]
> @shaneeza @TheSonOfThomp there are more tokens than hex colors hard-coded in the story file - how do we want to handle these colors moving forward?


You're referring to [these colors?](https://github.com/mongodb/leafygreen-ui/blob/main/packages/tokens/src/Tokens.story.tsx#L34-L42). Can we do what charts does and get a palette of N colors

**Comment by bruugey** [comment]
> > @shaneeza @TheSonOfThomp there are more tokens than hex colors hard-coded in the story file - how do we want to handle these colors moving forward?
> 
> Why do we need diff colors? Can we use the same color for all of them?

We could, what do you think @TheSonOfThomp

**Comment by TheSonOfThomp** [comment]
> > > @shaneeza @TheSonOfThomp there are more tokens than hex colors hard-coded in the story file - how do we want to handle these colors moving forward?
> > 
> > 
> > Why do we need diff colors? Can we use the same color for all of them?
> 
> We could, what do you think @TheSonOfThomp

Yeah, I don't see a need for them to be different

**Comment by bruugey** [comment]
> > > > @shaneeza @TheSonOfThomp there are more tokens than hex colors hard-coded in the story file - how do we want to handle these colors moving forward?
> > > 
> > > 
> > > Why do we need diff colors? Can we use the same color for all of them?
> > 
> > 
> > We could, what do you think @TheSonOfThomp
> 
> Yeah, I don't see a need for them to be different

So what color?

**Comment by TheSonOfThomp** [comment]
> > > > > @shaneeza @TheSonOfThomp there are more tokens than hex colors hard-coded in the story file - how do we want to handle these colors moving forward?
> > > > 
> > > > 
> > > > Why do we need diff colors? Can we use the same color for all of them?
> > > 
> > > 
> > > We could, what do you think @TheSonOfThomp
> > 
> > 
> > Yeah, I don't see a need for them to be different
> 
> So what color?

Whatever you want... I'd say `green.base` or `purple.light1`?

**Review by bruugey — APPROVED** [review]

**Pull request merged**
