### PR TITLE
Expose scroll to index functionality in table

### PR DESCRIPTION
**Pull request by khelif96**
## ✍️ Proposed changes

We would like to expose the `scrollToIndex` method in the @leafygreen-ui/table virtualization library to allow the table to programmatically scroll to a certain row. 

🎟 _Jira ticket:_ [Name of ticket](https://jira.mongodb.org/browse/[name-of-ticket])

### For bug fixes, new features & breaking changes

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have run `yarn changeset` and documented my changes

### For new components

- [ ] I have added my new package to the global tsconfig
- [ ] I have added my new package to the Table of Contents on the global README
- [ ] I have verified the Live Example looks as intended on the design website.

### CODE REVIEW

**Review by TheSonOfThomp — APPROVED** [review]
Makes sense. LGTM 👍

**Comment by khelif96** [comment]
@TheSonOfThomp is there anything I need to do to merge and release?

**Comment by TheSonOfThomp** [comment]
Not on your end, no. (We're working on figuring out how to get the CI checks to run properly)

Since you've included a changeset file, once merged into main this will be published on our next publish (Thursday, I believe)

**Comment by TheSonOfThomp** [comment]
Closing as duplicate

**Pull request closed without merging**
