### PR TITLE
PD-2073 text input focus ring

### PR DESCRIPTION
**Pull request by TheSonOfThomp**
## ✍️ Proposed changes

Aligns TextInput focus & hover styles with Figma Library. Uses `tokens.focusRing` and `tokens.hoverRing`

🎟 _Jira ticket:_ [Name of ticket](https://jira.mongodb.org/browse/[name-of-ticket])

## 🛠 Types of changes

- [ ] Tooling (updates to workspace config or internal tooling)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Style change (purely visual updates; if this is the case, attach a screenshot below!)

## ✅ Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] I have run `yarn changeset` and documented my changes

- [ ] I have added my new package to the global tsconfig
- [ ] I have added my new package to the Table of Contents on the global README

## 🧪 How to test changes

Verify for Light & Dark Mode:
- Hover Styles 
- Focus Styles
- Valid State hover & focus styles
- Error State focus & hover styles

## Feedback Levels

Please try to mark your comments with one of these levels

1. Praise (👏 🚀 🔥 🍾)
2. Opinions, Ideas, Suggestions (💡 👀)
3. Let’s discuss @ Code review (🤷 🤔 🧐 )
4. Doesn’t meet agreed upon standards (😬 ⚠️ ‼️)
5. Missing an edge case (🛑 🙅 ❌)
6. Missing core functionality (⛔️ ☣️ 🚧 🌋 💀)

(Note: Use ⌘-⌃-␣ to open the Emoji keyboard!)

### CODE REVIEW

**Review by shaneeza — COMMENTED** [review]
This is what im seeing in darkmode

Screen Shot 2022-08-03 at 2 40 22 PM

**Comment by TheSonOfThomp** [comment]
> This is what im seeing in darkmode when I hover over the autofill dropdown

Hmm, I'm not able to reproduce that. Regardless, we don't really control the size & position of the autofill box, just how the input looks when the autofill has appeared

Screen Shot 2022-08-03 at 6 21 31 PM

**Comment by shaneeza** [comment]
@TheSonOfThomp what happens if you click on `las vegas offsite...`? When the dropdown is open the background color is fine but it turns white when I make a selection.

**Comment by TheSonOfThomp** [comment]
@shaneeza Found where this was coming from. Ready for another look

**Review by shaneeza — APPROVED** [review]
Looks good!

**Pull request merged**
