### PR TITLE
Support Polymorphic React Server Components

### PR DESCRIPTION
**Pull request by jlarmstrongiv**
## ✍️ Proposed changes

React Server Components do not support React Client Component APIs, such as `React.createRef`.  By renaming and exposing two internal hooks (`usePolymorphicComponent` and `useInferredPolymorphicComponent`), we can support React Server Components, too.

🎟 _Jira ticket:_ [Community](https://jira.mongodb.org/browse/)

### For bug fixes, new features & breaking changes

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have run `yarn changeset` and documented my changes

## 🧪 How to test changes

I manually tested my changes with Next.js 13 in the experimental app directory.  Also, I studied the code to ensure no other React Client Component APIs were used.

### CODE REVIEW

**Review by TheSonOfThomp — APPROVED** [review]
Hi John, thanks for the PR! I'll pull this down myself and add some additional documentation, but otherwise it looks good.

I'm curious how you found this repo? Have you used it in a project of yours? We typically don't see usage outside of MongoDB

**Comment by jlarmstrongiv** [comment]
> Hi John, thanks for the PR! I'll pull this down myself and add some additional documentation, but otherwise it looks good.

Great!  Thank you for your help merging this PR.

> I'm curious how you found this repo? Have you used it in a project of yours? We typically don't see usage outside of MongoDB

I spent a few days trying different polymorphic react implementations out—my goal was implementing an `as` prop for a custom `styled` api.

Some approaches came from blogs, some from libraries, but none of them covered all of my use cases.  In fact, I recognized most of the prior art listed https://github.com/mongodb/leafygreen-ui/tree/main/packages/polymorphic#prior-art

I even stitched together my own version, but that didn’t cover all the use-cases either.  My last attempt was trying the [`@leafygreen-ui/polymorphic`](https://www.npmjs.com/package/@leafygreen-ui/polymorphic) package, since it sounded exactly what I was looking for—and it worked!

I open-sourced and published the library [here](https://www.npmjs.com/package/rcva), but I’m sure I’ll be using [`@leafygreen-ui/polymorphic`](https://www.npmjs.com/package/@leafygreen-ui/polymorphic) in my future projects too.

> We typically don't see usage outside of MongoDB

I was pleasantly surprised when I saw that [`@leafygreen-ui/polymorphic`](https://www.npmjs.com/package/@leafygreen-ui/polymorphic) was maintained by MongoDB.  I haven’t used your [design system](https://www.mongodb.design/) components specifically, but the polymorphic library solves the pain point that always comes up when I need to make a component both a `button` and link `a`.

In fact, I wanted to make an issue or discussion just to thank you for open-sourcing it, but those aren’t enabled.  So I’ll do it now—thank you!

**Comment by TheSonOfThomp** [comment]
I'm happy to hear this was helpful for you! It took a while for us to get it right 😊

**Comment by jlarmstrongiv** [comment]
@TheSonOfThomp thanks again for your help 😄 just updated to the latest version

**Pull request merged**
