### PR TITLE
Clean Storybook

### PR DESCRIPTION
**Pull request by brookescarlett**
- Remove Variants from sidebar of storybook, in favor of using `select knobs` to navigate between variant-options
- Not running changesets here, as this will not effect consuming applications
Screen Shot 2019-12-02 at 2 12 17 PM

### CODE REVIEW

**Comment by DesignerDave** [comment]
Can we also rename instances of `Default`? Right now we either say `Default` or the component's name.

**Comment by brookescarlett** [comment]
I actually think in most cases Default makes more sense than the component name, because where we are using multiple sub-tabs, it doesn't make sense to have one that says the component's name and one that says some variant of the component (IMO)

**Comment by brookescarlett** [comment]
Happy to standardize either way, but let me know if you think that makes sense @DesignerDave

**Comment by hswolff** [comment]
Using the new storybook standard format for storybook files may be a better time to do a rename as it has more flexibility I believe.

**Pull request merged**
