### PR TITLE
PD-2350 Updates TSDoc parse script

### PR DESCRIPTION
**Pull request by TheSonOfThomp**
## ✍️ Proposed changes

🎟 _Jira ticket:_ [Name of ticket](https://jira.mongodb.org/browse/[name-of-ticket])

## 🛠 Types of changes

- [x] Tooling (updates to workspace config or internal tooling)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Style change (purely visual updates; if this is the case, attach a screenshot below!)

## ✅ Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] I have run `yarn changeset` and documented my changes

- [ ] I have added my new package to the global tsconfig
- [ ] I have added my new package to the Table of Contents on the global README

## Feedback Levels

Please try to mark your comments with one of these levels

1. Praise (👏 🚀 🔥 🍾)
2. Opinions, Ideas, Suggestions (💡 👀)
3. Let’s discuss @ Code review (🤷 🤔 🧐 )
4. Doesn’t meet agreed upon standards (😬 ⚠️ ‼️)
5. Missing an edge case (🛑 🙅 ❌)
6. Missing core functionality (⛔️ ☣️ 🚧 🌋 💀)

(Note: Use ⌘-⌃-␣ to open the Emoji keyboard!)

### CODE REVIEW

**Review by spark33 — APPROVED** [review]
I like the changes! I'm interested to hear your thoughts on how you want to turn these into READMEs and .design code docs, maybe in the next code review (i.e. will it be done on build of each package? or maybe on release?)

**Comment by TheSonOfThomp** [comment]
> I like the changes! I'm interested to hear your thoughts on how you want to turn these into READMEs and .design code docs, maybe in the next code review (i.e. will it be done on build of each package? or maybe on release?)

I think generating the README files is a secondary concern for now, but should definitely happen soon. The priority for this PR is generating and shipping the `tsdoc`

**Comment by spark33** [comment]
I'm aware! That's why I approved the PR. I was just saying it would be interesting to hear at code review what you're building and how you intend to build it. Not to critique it or anything - just so we can be aware of what you're building and learn from the process. 😊

**Comment by TheSonOfThomp** [comment]
> I'm aware! That's why I approved the PR. I was just saying it would be interesting to hear at code review what you're building and how you intend to build it. Not to critique it or anything - just so we can be aware of what you're building and learn from the process. 😊

Makes sense! I'll definitely bring this to code review. From the discussion on Slack, it seems the future state would be to simply direct to `.design` from the Readme

**Comment by TheSonOfThomp** [comment]
We should filter the prop tables based on what's exported from index

**Pull request merged**
