### PR TITLE
LG-2202: Refresh Group 5

### PR DESCRIPTION
**Pull request by shaneeza**
## ✍️ Proposed changes

🎟 _Jira ticket:_ [LG-2202](https://jira.mongodb.org/browse/LG-2202)

[Modal](https://shaneeza.github.io/leafygreen-ui/?path=/story/components-modals-modal--controlled)
[Confirmation Modal](https://shaneeza.github.io/leafygreen-ui/?path=/story/components-modals-confirmationmodal--basic)
[Marketing Modal](https://shaneeza.github.io/leafygreen-ui/?path=/story/components-modals-marketing-modal--basic)
[Table](https://shaneeza.github.io/leafygreen-ui/?path=/story/components-table--basic)

## 🛠 Types of changes

- [ ] Tooling (updates to workspace config or internal tooling)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Style change (purely visual updates; if this is the case, attach a screenshot below!)

## ✅ Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have run `yarn changeset` and documented my changes

- [ ] I have added my new package to the global tsconfig
- [ ] I have added my new package to the Table of Contents on the global README

## Feedback Levels

Please try to mark your comments with one of these levels

1. Praise (👏 🚀 🔥 🍾)
2. Opinions, Ideas, Suggestions (💡 👀)
3. Let’s discuss @ Code review (🤷 🤔 🧐 )
4. Doesn’t meet agreed upon standards (😬 ⚠️ ‼️)
5. Missing an edge case (🛑 🙅 ❌)
6. Missing core functionality (⛔️ ☣️ 🚧 🌋 💀)

(Note: Use ⌘-⌃-␣ to open the Emoji keyboard!)

### CODE REVIEW

**Comment by sooachung** [comment]
Default select Modal: can we add 16px in between the body text and label? Also in between select inputs.
Screen Shot 2022-11-29 at 3 04 57 PM

Copyable Modal: also here (16px)
Screen Shot 2022-11-29 at 3 17 47 PM

**Comment by shaneeza** [comment]
> Default select Modal: can we add 16px in between the body text and label? Also in between select inputs. Screen Shot 2022-11-29 at 3 04 57 PM
> 
> Copyable Modal: also here (16px) Screen Shot 2022-11-29 at 3 17 47 PM

I can add this to the story but it's up to consumers to add the correct spacing.

**Comment by shaneeza** [comment]
@sooachung @audroue Marketing Modal is ready

**Review by alvenw — APPROVED** [review]

**Review by audroue — APPROVED** [review]
Alven & Soaa have reviewed these — I approve too!

**Review by brookescarlett — APPROVED** [review]

**Pull request merged**
